# Lecture 1: Jupyter Notebooks, lists, dictionaries, numpy arrays

Also see the tutorials for lists and dictionaries. This lecture will focus on Fun Things with Numpy arrays.

In [1]:
# Some typical list-based ways to do mathematical operations
a_list = [0.0, 1.0, 2.0, 3.0]
b_list = [-2.0, -1.0, 0.0, 0.2]

print(a_list)
print(b_list)

[0.0, 1.0, 2.0, 3.0]
[-2.0, -1.0, 0.0, 0.2]


In [3]:
# Perform a mathematical operation on each element in the list 
# In this case, 2 * x + 1
operate_on_a_list = []
for e in a_list:
    operate_on_a_list.append( 2 * e + 1)
print(operate_on_a_list)

[1.0, 3.0, 5.0, 7.0]


In [4]:
# Calculate the sum of a list
my_sum = 0
for e in a_list:
    my_sum += e
print(f"Sum: {my_sum}")

Sum: 6.0


In [5]:
# Add two lists together
add_lists = []
for a, b in zip(a_list, b_list):
    add_lists.append(a + b)
print(f"Adding lists: {add_lists}")

Adding lists: [-2.0, 0.0, 2.0, 3.2]


In [6]:
# See if 2.0 is in the list
b_found_two = False
for a in a_list:
    if abs(a - 2.0) < 1e-12:
        b_found_two = True
print(f"Found 2: {b_found_two}")

Found 2: True


## Just say NO to lists for mathematical operations on arrays of numbers
Use numpy.
Do numpy tutorial before lab.

In [7]:
import numpy as np

In [8]:
a_np_array = np.array(a_list)  # Shortcut way to create a numpy array from a list
b_np_array = np.array(b_list)
print(a_np_array)  # Notice different formatting
print(b_np_array)

[0. 1. 2. 3.]
[-2.  -1.   0.   0.2]


In [9]:
# Perform a mathematical operation on each element in the list 
# In this case, 2 * x + 1
operate_on_an_np_array = 2 * a_np_array + 1
print(operate_on_an_np_array)

[1. 3. 5. 7.]


In [10]:
# Calculate the sum of a list
print(f"Sum: {np.sum(a_np_array)}")

Sum: 6.0


In [11]:
# Add two lists together
print(f"Adding lists: {a_np_array + b_np_array}")

Adding lists: [-2.   0.   2.   3.2]


In [12]:
# See if 2.0 is in the list
all_twos = np.isclose(a_np_array, 2.0)
if all_twos.any():
    print("Found a 2")
print(f"Found 2: {all_twos}")

Found a 2
Found 2: [False False  True False]


## Dictionaries
See tutorial on dictionaries

In [13]:
# Notice curly brackets
my_dict = {"key 1": [-0.2, 0.2], "key 2": "value"}
print(my_dict)

{'key 1': [-0.2, 0.2], 'key 2': 'value'}


In [14]:
my_dict[3] = "Value for key 3"
print(my_dict)

{'key 1': [-0.2, 0.2], 'key 2': 'value', 3: 'Value for key 3'}
